In [13]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [14]:
dataset = pd.read_csv('DataSet_Test2.csv')
x = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [15]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.33, random_state = 0)

In [16]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [17]:
print(x_train)

[[ 1.17838525 -1.3568953   0.83696333 ... -0.07405558 -0.07839935
   1.73368477]
 [ 1.17838525  0.39816233  0.83696333 ... -0.07405558 -0.07839935
  -0.50494456]
 [-0.8486189   0.39816233  0.83696333 ... -0.07405558 -0.07839935
  -0.50494456]
 ...
 [-0.8486189   0.39816233  0.83696333 ... -0.07405558 -0.07839935
  -0.50494456]
 [ 1.17838525  0.39816233 -1.19479548 ... -0.07405558 -0.07839935
  -0.50494456]
 [-0.8486189   0.39816233 -1.19479548 ... -0.07405558 -0.07839935
  -0.50494456]]


In [18]:
print(x_test)

[[-0.8486189   0.39816233 -1.19479548 ... -0.07405558 -0.07839935
  -0.50494456]
 [-0.8486189   0.39816233 -1.19479548 ... -0.07405558 -0.07839935
  -0.50494456]
 [-0.8486189   0.39816233 -1.19479548 ... -0.07405558 -0.07839935
  -0.50494456]
 ...
 [ 1.17838525  0.39816233  0.83696333 ... -0.20144258 -0.07839935
  -1.62425923]
 [-0.8486189   0.39816233  0.83696333 ... -0.07405558 -0.07839935
  -0.50494456]
 [-0.8486189   0.39816233  0.83696333 ... -0.07405558 -0.07839935
  -0.50494456]]


In [19]:
print(y_train)

[97  2  1 ...  1  1  2]


In [20]:
print(y_test)

[ 2 99  2 99  2  1 99  2 97 97  1 97 97 99  2 97  2 97  2  2 97  2  2  2
 97  1  2  1  1  1 97 97  2  1  1  2  2 97  2  2 97  2  2 97  2  1  2 97
  2  2  2  2 97  1 97  2  2  2  2  2  2  2 97  2 97  2  1  2  1  2 97  1
 97 99  1 99 97 97 99  2  2 97  2  2  2 97  1 97  2 97  2  2 97  2  2 97
 97 97 97 97 97  1  2  2 97 97  2  2  2  2  2 97  2  2  2  2 97 97  1  2
  2 97 97  2 99  2  1  2  1 97  2 97 97 97  2  2  2  2 99 97  2  2  2  2
 97  2  2 97  2  1  2 97  2  1  2  2 97  2  2  2  2  1  2  2 97  2 97 97
  2  2  2  2 97 99  2  2  2  2  2  2 99  2 97 97  2 99  2  2 97 97 97  2
  2  2  2  2  2  2  2  2  2  1  1  1  1  1  2  2  2  2 97  2  1 99 97 97
  2 97  2  2  2  2  2  2  2  1 97  2  2 97  2 97 99  2  2 97  2  2 97  1
  1 99  2  2  2  2 97  2  1 97  2  2 97 99  2  2  2  2  2 97 97 97  2  2
  2  2  1 97  2  2  1  2  2 97  2  2  2 97 99  2  2  2  2  2  1  2  2  2
 97  2 97  2 97 97  1  2 99  2  2  2  2  1  2  2  2  2  2 97  2  1 97  2
  1  1  2  2  2  2  2  2  2 97  2  1  2  2  2  2  2

In [21]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [22]:
y_pred = classifier.predict(x_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[ 2  2]
 [99 99]
 [ 2  2]
 ...
 [ 2  2]
 [ 2  2]
 [ 2  2]]


In [23]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[ 30  58   0   0]
 [ 35 331   0   0]
 [  0   0 173   0]
 [  0   0   0  33]]


0.8590909090909091

In [24]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           1       0.46      0.34      0.39        88
           2       0.85      0.90      0.88       366
          97       1.00      1.00      1.00       173
          99       1.00      1.00      1.00        33

    accuracy                           0.86       660
   macro avg       0.83      0.81      0.82       660
weighted avg       0.85      0.86      0.85       660



In [26]:
from sklearn.metrics import mean_absolute_error
print(mean_absolute_error(y_pred,y_test))

0.1409090909090909
